# Generated by Django 5.2.8 on 2025-12-15 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_user_bg_alter_user_avatar_alter_user_user_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_tag",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Username pode conter apenas letras, números, ".", "_" e "-".',
                        regex="^[a-zA-Z0-9._-]+$",
                    )
                ],
            ),
        ),
    ]
